---
name: Fetch

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '*-20*'

jobs:
  Fetch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        day: [2]
        month: [2]
        year: [2020]
        pair: [EURUSD]
    steps:
      - uses: actions/checkout@v2
      - uses: fx31337/fx-data-download-action@master
        with:
          Days: ${{ matrix.day }}
          Months: ${{ matrix.month }}
          Years: ${{ matrix.year }}
          Pairs: ${{ matrix.pair }}
      - name: Print CSV files
        run: find . -name "*.csv" -print
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CSV
          path: '**/*.csv'
